Add support on the server to set new animation types for the meditation
ao-org/argentum20-server pull request #123
Opened 2022-07-28 20:27 UTC by matiascalegaris

2022-07-28 20:41 UTC, RecoX submitted a review, later dismissed

2022-07-28 21:04 UTC, morgolock commented
Please lets avoid adding columns to existing tables, which can lead to performance degradation in queries.

Let's rework the patch to address this problem.

2022-07-28 21:05 UTC, morgolock requested changes

2022-07-29 04:59 UTC, morgolock commented on Codigo/InvUsuario.bas
> +
if Slot < 0 or slot > MAX_SLOT exit sub

2022-07-30 21:53 UTC, morgolock approved these changes

2022-07-30 21:54 UTC, merged