Control de macro en ocultar
ao-org/argentum20-server pull request #178
Opened 2022-10-16 01:35 UTC by ReyarB

Prueba de automatizar penas, por ahora el ocultar con mas de 6 interacciones sabemos que no se logran con el teclado apretando "O"

2022-10-16 21:10 UTC, matiascalegaris commented on Codigo/Protocol.bas
> +
lo unico que me preocupa de este cambio es que pueda pasar por un tema de lag, @morgolock alguna idea de como probarlo para estar seguros?

2022-10-16 21:25 UTC, matiascalegaris commented on Codigo/Declares.bas
> +
change to MaxHidePacketIteration

2022-10-16 21:25 UTC, matiascalegaris commented on Codigo/FileIO.bas
>  140     DisconnectTimeout = val(Lector.GetValue("INIT", "DisconnectTimeout"))
update to MaxHidePacketIteration

2022-10-16 21:25 UTC, matiascalegaris commented on Codigo/Protocol.bas
> +
si mandamos encarcelamos aca deberiamos mandar un mensaje al useario de porque fue encarcelado

2022-10-17 06:29 UTC, morgolock requested changes
No se puede automatizar, la latencia de la red cambia y las iteraciones tambien. Esto va a encarcelar gente inocente.

2022-10-17 18:13 UTC, closed without merging