Refactor npc references
ao-org/argentum20-server pull request #200
Opened 2022-11-11 21:50 UTC by matiascalegaris

2022-11-14 22:31 UTC, morgolock requested changes

2022-11-14 22:31 UTC, morgolock commented on Codigo/MODULO_NPCs.bas
> +    If NpcRef.ArrayIndex <= 0 Or NpcRef.ArrayIndex > UBound(NpcList) Then
Instead of `If NpcRef.ArrayIndex <= 0` maybe better `If NpcRef.ArrayIndex < LBound(NpcList)`

2022-11-14 22:31 UTC, morgolock commented on Codigo/MODULO_NPCs.bas
> +    If Index <= 0 Or NpcRef.ArrayIndex > UBound(NpcList) Then
Replace `If Index <= 0 Or` by ` If Index <= LBound(NpcList) or`

2022-11-14 23:32 UTC, matiascalegaris commented on Codigo/Declares.bas
> +Public Type t_NpcReference
we may create a new one for both but i still think we need to have this separate for error checking like unique_ptr<Npc> and unique_ptr<User>

2022-11-14 23:34 UTC, matiascalegaris commented on Codigo/AI_NPC.bas
> +128             Call SetNpcRef(.TargetNPC, BuscarNpcEnArea(NpcIndex))
its the same if we set -1 as parameter it will set the reference as invalid

2022-11-15 18:49 UTC, morgolock approved these changes

2022-11-15 18:49 UTC, merged