Seguro para ataque de npcs de ciudadanos (limpie el branch para simplificar)
ao-org/argentum20-server pull request #402
Opened 2023-09-27 22:58 UTC by carlospaezp

2023-09-28 20:21 UTC, matiascalegaris requested changes

2023-09-28 20:31 UTC, carlospaezp commented on Codigo/modHechizos.bas
> -120                 Call WriteConsoleMsg(UserIndex, "Solo puedes invocar una sola criatura de este tipo.", e_FontTypeNames.FONTTYPE_INFO)
No, es la misma logica actual, solo que actualemnte si tenes un elemental de tierra invocado, salta el msg de arriba que dice: Ya tienes un elemental de este tipo invocado, lo cual es erroneo, entonces si tenes uno de tierra y queres invocar uno de fuego, te deberia dejar, pero no otro de fuego o fatuo o de estos, entonces de esta manera, sigue la misma logica, pero no te bloquea poder invocarlo.

2023-10-02 20:42 UTC, morgolock commented on Codigo/MODULO_NPCs.bas
> +
@carlospaezp podes implementar los cambios sugeridos? nos gustaria aprobar tu PR pero necesita algunos cambios.

2023-10-03 14:10 UTC, carlospaezp commented on Codigo/MODULO_NPCs.bas
> +
ok, habia hablado con tute y el queria hacer un cambio mas fuerte sobre esa funcion, pero temporalmente puedo simplificarla al menos y unir esas 2

2023-10-03 14:25 UTC, matiascalegaris commented on Codigo/MODULO_NPCs.bas
> +
mira justo estoy haciendo un mini refactor de esto asi sacamos todo esto duplicado, te aviso cuando suba el pr porque tuve que tocar esto justo

2023-10-04 01:33 UTC, carlospaezp commented on Codigo/MODULO_NPCs.bas
> +
Subido los cambios con el refacto de la funcion de PuedeAtacarNPC, unifique las 2, y le puse un type nuevo con los parametros necesarios para las distintas acciones..
De yapa tb meti un fix que te permite vender items a los npcs vendedores que ellos venden, ahora mismo hay un bug que el carpintero por ejemplo vende flechas, pero no te permite volver a venderselas.

2023-10-04 21:42 UTC, matiascalegaris requested changes

2023-10-04 21:42 UTC, matiascalegaris commented on Codigo/modHechizos.bas
> +
necesitamos tener en cuenta el testeo en "puedelanzar" no llegamos aca, probablemente todo estos chequeos aca ya no hagan falta, fijate en PuedeLanzar entre 126 y 128 hay un blqoue de codigo que ya tiene en cuenta esto

2023-10-05 20:44 UTC, matiascalegaris approved these changes

2023-10-05 20:47 UTC, merged