Fix when attack send heading to avoid issues when lagged
ao-org/argentum20-server pull request #431
Opened 2023-10-23 02:35 UTC by carlospaezp

2023-10-23 22:45 UTC, morgolock requested changes

2023-10-23 22:45 UTC, morgolock commented on Codigo/Protocol.bas
> +            Heading = Reader.ReadInt8
This is not a good idea, we cannot add a heading to the Attack command. We want to maintain simplicity and also this opens a potential risk for cheating.

2023-10-24 14:15 UTC, carlospaezp commented on Codigo/Protocol.bas
> +            Heading = Reader.ReadInt8
What cheating can they do with that?, right now there is an issue that when you are attacking the client doesn't correspond with the server and you are looking at the npc but not hitting it, I saw several new players asking why they were not hitting the npc, and it's usually related to lag, sending the heading when attacking will force the user to rotate in server if wrong, the same way you can rotate with arrow keys.

2023-10-24 16:08 UTC, morgolock commented on Codigo/Protocol.bas
> +            Heading = Reader.ReadInt8
This is not a good solution and is not solving the underlying problem: there is a mismatch between the heading in the server and the client. There is a problem somewhere else causing this mismatch in the heading between the client and the server.

The problem is not related to lag since an attack packet cannot arrive out of order before a change of heading. The order of packets is enforced by TCP and they are guaranteed to arrive in FIFO order.

We cannot add the heading to the attack packet because:

1. It introduces additional complexity to the protocol: melee attacks must always happen in the direction the PC is facing. We must keep the protocol simple.

2. Opens the possibility for cheats and doing things like attacking to in a direction a character is not facing without previously changing the heading. (cheats can exploit this)

2023-10-24 16:08 UTC, closed without merging