Integrate Epic EOS anti cheat
ao-org/argentum20-server pull request #433
Opened 2023-11-02 04:00 UTC by matiascalegaris

2023-11-04 21:00 UTC, morgolock requested changes

2023-11-04 21:00 UTC, morgolock commented on Codigo/AntiCheat.bas
> +Attribute VB_Name = "AntiCheat"
Please add the licence header to any new files

2023-11-05 21:04 UTC, morgolock requested changes
Is there no way to disable the Anti cheat code when compiling like in the client with a define?

2023-11-05 21:04 UTC, morgolock commented on Codigo/Protocol.bas
> -    Exit Sub
We should not remove `exit sub`

2023-11-06 00:26 UTC, matiascalegaris commented
> Is there no way to disable the Anti cheat code when compiling like in the client with a define?

the anti cheat is disabled by default under a featuretoggle, no need to build flag

2023-11-06 23:58 UTC, merged